### ISSUE TITLE
Implement MessageEmitter

### ISSUE THREAD

**Issue by AlexBedley** [AlexBedley/QuestionBot#3]
(Make sure #2 is completed before starting this work)
1. Create an interface `IMessageEmitter` with the following functions:
   - `Add` which takes an `IMessageListener` as a parameter and returns void
   - `Start` which takes no parameters and returns void
2. Create a class `MessageEmitter` that implements `IMessageEmitter`
   - When `Start` is called, `MessageEmitter` should continually call `Console.ReadLine` and call `ReceiveMessage` with the result to all `IMessageListener` that were added with `Add`.
3. Add unit tests for `MessageEmitter`
4. Modify **Program.cs** to initialize an `IMessageEmitter` with a `QuestionMessageListener` and call `Start`. After this step, you should be able to run the program and continually ask questions until exiting.

**Comment by AlexBedley** [comment]
Aw you can't add emojis to events, only comments. But this event deserves a partay! 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉

**Comment by Stiffni** [comment]
hahaha, on to the next issue! woowoo!
